// AUTOGENERATED, DO NOT EDIT

namespace XRInternal {
namespace XRAutoGenerated {
public class XRMobileAppKey {
  // %key% will be replaced with the editor-supplied value on build.
  public const string KEY = "f10Xp1a8eGeCe0p9Um3EWwTyPV7B9yNPdEKx3dr29Do3Spacjos3qhkiBZoV0CnT6aJ40I";
}
}
}

